---
title: "Collaboration"
author: "Brian Weatherson"
date: "3/18/2022"
output: html_document
---

I'm going to discuss two very broad kinds of collaboration - co-authorship, and providing assistance. 

### Co-Authorship

For a long time, philosophy had much lower rates of co-authorship than cognate disciplines. Thankfully that's changing, though it is changing slowly. Still, you can see very successful people across the top programs whose careers have largely been built on co-writing papers.

One kind of model for this is where two people (or occasionally three) have a long-running research partnership. A notable local(ish) version of that is Justin D'Arms and Dan Jacobson's work, going back I believe to their time together in grad school. Those partnerships are great, if you can be part of one, but rare enough that we don't need to spend a ton of time on them.

Another model is places where philosophy largely gets done by talking about ideas until some subset of the group feels like writing them up as a paper/book. You see versions of this model at Rutgers, USC and, most especially, ANU.

And yet another model is where collaborations are one-off works between two people whose interests overlap enough on this point that it's worth writing the paper together. That's the most likely way you'll end up co-authoring papers, and it's sort of the default I'll talk about here, though the other two cases are relevant too.

The biggest thing I want to stress is that co-authoring papers is great and you should do more of it. You learn a lot from interacting that intensively with a peer. If you have different strengths, the papers can benefit from each of them. And it's a way of reducing the isolation of the research parts of graduate school. You do ultimately have to write your dissertation - though even that can include co-authored papers - and because of that grad school can push you towards solo work. But philosophy is best done collaboratively, and we all should try to be more collaborative in our work. So if you take one thing away from these notes, it's that: do more collaborative work.

That said, here are so dos and don'ts, and some general advice, about co-authorship.

- Do make sure that both parties (or all parties if there are more than 2 authors) put in a fair share of the work. Sometimes you can put a lot of work into a paper, and really the fair compensation is a very generous acknowledgment. To be a co-author should require a bit more than that.
- Do not require that each party does the same work. That defeats the whole division of labor part of the benefits is that you can benefit from different people contributing different skills. So a split where one person drafts and the other edits is fine. (I'm much much better at drafting than editing, so this is my favorite division of labor.) A split where one person does the mathematical work and the other person does the writing is also fine, if the mathematical work is a big chunk of the paper. So is a split where one person does the historical work, and the other does the more contemporary work, if there is substantial historical work in the paper. And so are any number of other splits. Note that the fairness requirement is easier to satisfy in long-term collaborations; all that matters is that each party does their fair share across the papers.
- Do make sure that everyone endorses the conclusions of the paper, at least to the extent that one ever endorses the conclusion of a philosophy paper. This can make collaborations with more than 2-3 people very hard to make work. It's possibly not best that this is the norm in philosophy, but it is - you have to endorse the paper even if you're not the main author.
- Do put the authors in alphabetical order unless there is a very good reason to do otherwise. Philosophy doesn't have the lead author/other authors distinction. Anything other than alphabetical order is a strong indication that one person did a lot of the work.
- Do not think that _having the original idea_ is a huge part of doing one's fair share of the work. Paper writing is hard - lots of people have ideas. Having the original idea doesn't absolve you from future work, doesn't make it more your paper than anyone else's, doesn't make you the main author, and so on. Thinking otherwise is a particularly pernicious manifestation of the 'cult of genius', which we should all be trying to get away from.

And here are three things to worry about, some of which you can mitigate by thinking/talking about them ahead of time.

- In some parts of the world, there is a bad habit of advisors 'co-authoring' papers with advisees where the advisee does a lot of the work, and the advisor gets a cheap publication. I don't think that's a problem around here. But just in case it ever comes up, in collaborations between advisors and advisees, or really any other kind of power imbalance, the distribution of work should be such that it is unambiguously clear the more powerful party did their fair share of the work. When I was a grad student, I got an incredible amount of assistance in writing my paper on intuitionistic probability from Lloyd Humberstone. If I'd gotten that much help from another student, they would have deserved a co-authoring credit. But it's fine, I think, for a faculty member who puts that much work in to get a generous acknowledgment.
- One thing that goes wrong even in relatively successful co-authorships is that the parties have different goals for how this paper fits into a larger research project. This can be a challenge when you are thinking about what to put in/leave out. Sometimes if you're working on your own papers, there is something that you don't include in paper 1 because including  it would complicate writing paper 2. When paper 1 is co-authored, and paper 2 is solo-authored, it's a little harder to plan that. Anyway, if you're co-writing something that is somewhat central to your research project, think a bit about how this paper fits into that larger project, and don't cannibalise your future research for this paper.
- Another thing that goes wrong, related perhaps to the first two, is that the parties to the project have different levels of commitment to the project, and this causes problems if the project gets harder than imagined. This can happen when (a) the paper gets rejected by the first few places you send it, or (b) the paper turns out to require much more background research than you'd realised at first. It might be worthwhile having a chat early on in the project to calibrate everyone's commitment levels to the project. This is especially pressing if your model of how to co-author papers is Go to lunch -> Talk philosophy -> Notice interesting ideas -> Write them into a paper. (A non-trivial number of my co-authored papers come from long lunches.) It's a lot easier to get excited by ideas over lunch than it is to plan what you'll do after the fourth journal rejection, so sometimes this problem can get put off. But it's good to at least have a little think about it.

None of this is meant to stop you co-authoring papers. As I've said, I think it's a very good way to do philosophy. The reading groups/discussion groups around here have lots of good ideas in them - people should write some of those ideas up!

### Support

Here's the big message I want you to take away from this section.

> **Giving people feedback on their work is a way of collaborating on their project**

That goes in reverse too - people you get feedback from are your collaborators. A lot of things follow from these principles. A big one is that when you're at a grad student talk, or at a reading group on a paper by another student, a big aim should be to help the project along. And I mean that to contrast with the aims of trying to win an argument, or trying to prove that you're the smartest person in the room, or trying to fulfill an obligation.

This doesn't mean that you shouldn't raise objections - you totally should. There is a reason that people engage in 'adversarial collaboration'. And sometimes the best advice to give someone is that the project isn't working, and they should try something else. But still, the aim is to help.

So think a bit about what styles of feedback are helpful. One thing I think follows from this way of thinking about things is that clarification questions are often very helpful. Knowing that it's unclear whether you meant X or Y, and that some people took it one way and other people another, can be very useful. And perhaps you (the speaker) didn't even distinguish between X and Y, so a request for clarifying which you mean is very good indeed. Another thing is that questions about how this project relates to other projects can be very useful. These can often seem like annoying questions - _So that was a nice paper, but let's talk about how it relates to my work_ - but I think they can lead to productive exchanges.

Sometimes the best way to help the speaker is not to ask a question, but to follow up in writing afterwards. You can probably think of a million kinds of cases in which this is true, but here are two that come up a bit. If there is a very technical objection you want to make, it's often much easier to follow it in writing than spoken. And if there is some relevant literature that the speaker has simply missed, it sometimes can spare blushes to point them to it not in everyone else's presence. More generally, when you're at talks with other grad students, think about ways in which you can provide useful feedback after the talk, either instead of or as well as during it.

Another way to help the speaker is to simply note down the questions and answers at any given talk. Personally, I can almost never remember most of the questions/answers at a talk, which does somewhat reduce the value of doing talks. But someone noting down even the bare outlines of what was said can be enough to recall the important points. I strongly recommend that at grad student presentations you have someone whose job it is to basically take minutes - keep a rough record of what was said. Barring that, you should make arrangements with other students to keep notes on each other's talks, or even just take notes for others. It is a bit of work, but it isn't the worst way to keep concentration on what's going on during a talk, and it's really valuable.

Finally, think about whether you are doing your fair share of helping others, given how much help you get from others. This doesn't mean that every time someone helps you (e.g., by providing useful feedback on a paper), you have to help them. You have to thank them, but you don't necessarily have to help them in the same way. Often, the best way to be helpful is to pay it forward. If you've benefited from the existence of reading groups organised by others, then organise something similarly useful in later semesters/years. If you got help from senior grad students when you were a junior grad student, well in not very long you'll be the senior grad student who can provide the same kind of help to junior grad students. The point is not that there should be some ledger carefully tallying up everyone's moral debits and credits to each other person. The point, rather, is that everyone should do their fair share in helping the community thrive. And to work out whether you are doing your fair share, think about what you've gained from other people's volunteer efforts, and try to contribute something similar. Fairness, as you probably know, is a pretty elastic concept. It doesn't require the person who is hospitalised with a serious illness to do the same amount as the person whose life is going more smoothly. For that reason, among many others, it doesn't require an exact match between what each person puts in and what help that person gets. So don't try to aim for exactly that. But do go to talks by other students, organise a reading/writing group here or there, and help create the kind of philosophical community you'd like to be a part of. This has obviously been very hard to do during the pandemic, but hopefully going forward we can build a better community, and we'll all gain a lot from it.
